[development]
ORTHANC_API_URI = "YOUR_ORTHANC_URI"
REDIS_URI = "YOUR_REDIS_URI"
REDIS_CACHE_TIME = 10
ES_STUDIES_INDEX_PREFIX = "YOUR_STUDY_INDEX"
ES_PROJECTS_INDEX_PREFIX = "YOUR_PROJECT_INDEX"
ELASTICSEARCH_HOST = "YOUR_ES_URI"
VINDR_LAB_URI = "YOUR_API_URI"
VINDR_LAB_API_KEY = "YOUR_SECRET_API_KEY"
ID_GENERATOR_URI = "YOUR_IDGEN_URI"
PUBLIC_KEY_PATH = "PATH_TO_PUBKEY"
